language: ruby
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.11.2

script: "bundle exec rake"

install: bundle install --retry=3 --jobs=3

gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile

deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: graphiti_errors
  on:
    tags: true
    repo: graphiti-api/graphiti_errors
