language: ruby
rvm:
- 2.4
- 2.5
- 2.6

gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile

before_install: gem install bundler -v 1.11.2
install: bundle install --retry=3 --jobs=3

env:
  - COMMAND=standardrb --no-fix --format progress
  - COMMAND=rspec

script:
  - bundle exec $COMMAND

deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: graphiti_errors
  on:
    tags: true
    repo: graphiti-api/graphiti_errors
